name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_followup: yes
          plugin_lines: yes
          plugin_followup_sections: repositories, user #
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 1000
          commits_authoring: xenos1337@users.noreply.github.com
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000 
          plugin_reactions_details: count, percentage
          plugin_reactions_ignored: bot
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
