name: Metrics
on:
  schedule: [{cron: "* 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_followup: yes
          plugin_lines: yes
          plugin_followup_sections: repositories, user #
          plugin_languages: yes
          plugin_languages_details: lines
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 3
          commits_authoring: xenos1337@users.noreply.github.com
          plugin_activity: yes
          plugin_activity_limit: 2
          plugin_activity_days: 0
          plugin_activity_filter: all
