name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_introduction: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 10000
          plugin_achievements: yes
          plugin_achievements_display: compact
